services:
  builder:
    image: ${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder:${TAG_FROM_GIT_REF_NAME:-latest}
    build:
      dockerfile: onbuild.Dockerfile
      target: base
      tags: 
        - ${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder:${TAG_FROM_GIT_REF_NAME:-latest}
        - ${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder:${TAG_FROM_GIT_SHA:-latest}
      x-bake:
        cache-from:
          # duplication is due to workaround for
          # missing multi-node registry cache, tracked in #218
          - "type=registry,ref=${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder/cache/linux/arm64:${TAG_FROM_GIT_REF_NAME}"
          - "type=registry,ref=${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder/cache/linux/amd64:${TAG_FROM_GIT_REF_NAME}"
          - "type=registry,ref=${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder/cache/linux/arm64:${DEFAULT_BRANCH}"
          - "type=registry,ref=${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder/cache/linux/amd64:${DEFAULT_BRANCH}"
        cache-to:
          # workaround for missing multi-node registry cache, tracked in #218
          - "type=registry,ref=${REGISTRY_PREFIX_GHCR}/${IMAGE_OWNER}/${IMAGE_NAME_ROOT}/onbuild/builder/cache/${ARCH:-linux/amd64}:${TAG_FROM_GIT_REF_NAME},mode=max"
