on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]

jobs:
  build-builder:
    # this step is only necessary for this image
    name: Build and Push Builder Image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: docker/build-push-action@v1
        with:
          # by convention, the same
          repository: ${{ github.repository }}
          dockerfile: builder.Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          tag_with_ref: true
          tag_with_sha: true
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
