on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]

jobs:
  build-onbuild:
    # this job is only necessary for this image
    name: Build and Push Onbuild Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Buildtime Onbuild Image
        uses: docker/build-push-action@v1
        with:
          # by convention, the same
          repository: ${{ github.repository }}-buildtime-onbuild
          # must be pushed to docker hub, not docker.pkg.github.com because latter is private, which cannot be used in `container` field.
          dockerfile: builder_img/builder.Dockerfile
          target: buildtime
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Build and Push Runtime Onbuild Image
        uses: docker/build-push-action@v1
        with:
          # by convention, the same
          repository: ${{ github.repository }}-runtime-onbuild
          # must be pushed to docker hub, not docker.pkg.github.com because latter is private, which cannot be used in `container` field.
          dockerfile: builder_img/builder.Dockerfile
          target: buildtime
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
  CICD:
    needs: build-onbuild
    runs-on: ubuntu-20.04
    defaults:
      run:
        shell: Rscript {0}
    # github sha only necessary here
    container: ${{ github.repository }}-buildtime:${{ github.sha}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          # only cache the user library
          # unfortunately cannot retrieve this programmatically without a separate step read out env var or installing github action npm to image
          path: ".github/library"
          # querying dependencies against CRAN is unnecessary, because they are all locked down via RSPM
          # TODO use job.container here elsewhere for other packages
          key: ${{ hashFiles('DESCRIPTION') }}
      - name: Install System Dependencies
        run: muggle::install_sysdeps()
      - name: Install R Dependencies
        env:
          # see builder.Dockerfile for explanation, this resets after this step
          R_LIBS_SITE: $R_LIBS_APP_GH
        run: remotes::install_deps(dependencies = TRUE)
      - name: Check
        run: muggle::rcmdcheck2()
      - name: Test Coverage
        run: covr::codecov()
      - name: Build Package Website
        run: pkgdown::build_site(override = list(new_process = FALSE))
      - uses: docker/build-push-action@v1
        name: Build Buildtime Image
        with:
          repository: ${{ github.repository }}/muggle-buildtime
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # only necessary here
          build_args: MUGGLE_BUILDER_TAG=${{ github.sha }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          # we're relying on long shas only to keep things easy
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@github-token
        env:
          BUILD_DIR: docs
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
