on:
  push:
  pull_request:
    types: [assigned, opened, synchronize, reopened]
  release:
    types: [published, created, edited]

jobs:
  build-onbuild:
    # this job is only necessary for this image
    name: Build and Push Onbuild Images
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build and Push Buildtime Onbuild Image
        uses: docker/build-push-action@v1
        with:
          # by convention, the same
          repository: ${{ github.repository }}-buildtime-onbuild
          # must be pushed to docker hub, not docker.pkg.github.com because latter is private, which cannot be used in `container` field.
          dockerfile: builder_img/builder.Dockerfile
          target: buildtime
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Build and Push Runtime Onbuild Image
        uses: docker/build-push-action@v1
        with:
          # by convention, the same
          repository: ${{ github.repository }}-runtime-onbuild
          # must be pushed to docker hub, not docker.pkg.github.com because latter is private, which cannot be used in `container` field.
          dockerfile: builder_img/builder.Dockerfile
          target: runtime
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
  CICD:
    needs: build-onbuild
    runs-on: ubuntu-20.04
    env:
      MUGGLE_PKG_NAME: ${{ github.event.repository.name }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    defaults:
      run:
        shell: Rscript {0}
    # github sha only necessary here
    container: ${{ github.repository }}-buildtime-onbuild:${{ github.sha}}
    steps:
      - uses: actions/checkout@v2
      - name: Cache R Packages
        uses: actions/cache@v2
        with:
          # only cache the user library
          # unfortunately cannot retrieve this programmatically without a separate step read out env var or installing github action npm to image
          path: ".github/library"
          # querying dependencies against CRAN is unnecessary, because they are all locked down via RSPM
          # use job.container here elsewhere for other packages
          # note there is never a need to invalidate the cache for changes in the upstream builder.Dockerfile or RSPM snapshot, because those are already in the container: above
          key: $${{ hashFiles('DESCRIPTION') }}
      - name: Install System Dependencies
        run: muggle::install_sysdeps()
      - name: Install R Dependencies
        env:
          # see builder.Dockerfile for explanation, this resets after this step
          R_LIBS_SITE: $R_LIBS_RUNTIME_GH
        run: remotes::install_deps(dependencies = TRUE)
      - name: Check
        run: devtools::check()
      - name: Test Coverage
        run: covr::codecov()
      - name: Build Package Website
        run: muggle::build_site2(override = list(new_process = FALSE))
      - uses: docker/build-push-action@v1
        name: Build Buildtime Image
        with:
          repository: ${{ github.repository }}/${{ env.MUGGLE_PKG_NAME }}-buildtime
          target: buildtime
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # only necessary here
          build_args: MUGGLE_BUILDER_TAG=${{ github.sha }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          # we're relying on long shas only to keep things easy
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Build Runtime Image
        # this isn't really needed, just for testing
        uses: docker/build-push-action@v1
        with:
          repository: ${{ github.repository }}/${{ env.MUGGLE_PKG_NAME }}-runtime
          target: runtime
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: docker.pkg.github.com
          # only necessary here
          build_args: MUGGLE_BUILDER_TAG=${{ github.sha }}
          # this will set "latest" if master as per https://github.com/docker/build-push-action
          tag_with_ref: true
          # we're relying on long shas only to keep things easy
          tag_with_sha: false
          tags: ${{ github.sha }}
          add_git_labels: true
          push: ${{ github.event_name != 'pull_request' }}
      - name: Log in to Azure
        uses: azure/login@v1.1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Deploy to Azure Webapps
        run: |
          muggle::az_webapp_config_muggle(
            name = "shiny-text",
            plan = "hoad",
            resource_group = "hoad",
            subscription = "f0dd3a37-0a4e-4e7f-9c9b-cb9f60146edc"
          )
      - name: Deploy to GitHub Pages
        if: github.ref == 'refs/heads/master'
        uses: maxheld83/ghpages@github-token
        env:
          BUILD_DIR: docs
