---
name: Onbuild

on:
  push:
  pull_request:

concurrency:
  # don't run on commits in quick succession on the same branch
  group: ${{ github.ref }}
  # ... except for main, where we want a full record of CI
  cancel-in-progress: ${{ github.ref_name != 'main' }}

jobs:
  build-onbuild:
    name: "Build Images with ONBUILD Instructions"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/amd64, linux/arm64"
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.4
          install: true
      - name: "Log in to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: "Build and Push Images"
        run: |
          make bake \
            tag_from_git_sha="${{ github.sha }}" \
            git_ref_name="${{ github.ref_name }}" \
            is_ci=true
  # workaround for missing multi-node registry cache, tracked in #218
  build-onbuild-armcache:
    name: "Build ARM64 Cache"
    runs-on: ubuntu-22.04
    steps:
      - name: "Checkout"
        uses: actions/checkout@v3
      - name: "Set up QEMU"
        uses: docker/setup-qemu-action@v2
        with:
          platforms: "linux/arm64"
      - name: "Set up Docker Buildx"
        uses: docker/setup-buildx-action@v2
        with:
          version: v0.10.4
          install: true
      - name: "Log in to GHCR"
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: "Build and Push ARM64 Image Cache"
        run: |
          ARCH="arm64" \
            make bake \
              tag_from_git_sha="${{ github.sha }}" \
              git_ref_name="${{ github.ref_name }}" \
              is_ci=true \
              bake_args="--set=*.platform=linux/arm64  --set=*.output='type=tar,dest=throwaway.tar'"
